services:
  ollama:
    image: 'ollama/ollama:latest'
    ports:
      - '11430:11434'
  postgres:
    image: 'postgres:16-alpine'
    environment:
      - 'POSTGRES_DB=mydatabase'
      - 'POSTGRES_PASSWORD=secret'
      - 'POSTGRES_USER=myuser'
    ports:
      - '54320:5432'
